/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Ticket;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Ticket Booking Starts!!");
        Scanner scanner = new Scanner(System.in);
        int option=0;
        UserBookingService bookingService;
        try{
            bookingService=new UserBookingService();
        } catch (IOException e) {
            System.out.println("IOException found");
            return ;
        }
        System.out.println("Select an option  from below:");
        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option=scanner.nextInt();
            switch (option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String userName=scanner.next();
                    System.out.println("Enter password to signup");
                    String password=scanner.next();
                    User u=new User(userName, password, UserServiceUtil.hashPassword(password), new ArrayList<Ticket>(), UUID.randomUUID().toString());
                    Boolean result=bookingService.signUpUser(u);
                    if(result) System.out.println("Successfully created an account!");
                    else System.out.println("These  credentials are already begin used . Please enter other credentials");
                    break;
                case 2:
                    System.out.println("Enter credentials for login!");
                    String username=scanner.next();
                    System.out.println("Enter passowrd");
                    String passWord=scanner.next();
                    User loginUser=new User(username,passWord,UserServiceUtil.hashPassword(passWord),new ArrayList<Ticket>(),UUID.randomUUID().toString());
                    try{
                        bookingService=new UserBookingService(loginUser);
                    }catch (IOException e){
                        System.out.println("IO Exception");
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetch bookings ");
                    bookingService.fetchBoookings();
                    break;
                case 4:
                    System.out.println("Enter source station");
                    String sourceStation=scanner.next();
                    System.out.println("Enter destination station");
                    String destinationStation=scanner.next();


            }
        }
    }
}
